version: 0.2

phases:
  install:
    commands:
      - npm install -g @0x4447/grapes@1.0.2
  build:
    commands:
      - grapes -b -s ./Stack_VPN_Contained
  post_build:
    finally:
      - aws s3 cp ./Stack_VPN_Contained/CloudFormation.json s3://0x4447-drive-cloudformation/vpn-contained.json --acl public-read
